### ISSUE TITLE
Broken: intellij-idea-community-bin

### ISSUE THREAD

**Issue by mortim** [pacstall/pacstall-programs#6731]
### Package name

intellij-idea-community-bin

### Version

2024.2.3-1

### Pacstall version

5.5.0 Rust

### Relevant log output

I have no problem installing the package, but when I run IntelliJ IDEA I got this error:

```shell
**Start Failed**

Internal error

java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
	at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:112)
	at com.intellij.openapi.application.PathManager.getBinDirectories(PathManager.java:145)
	at com.intellij.openapi.application.PathManager.loadProperties(PathManager.java:684)
	at com.intellij.idea.Main.mainImpl(Main.kt:57)
	at com.intellij.idea.Main.main(Main.kt:49)

-----
JRE: 21.0.4+13-b509.17 amd64 (JetBrains s.r.o.)
/usr/share/intellij-idea-community/jbr
```

**Comment by jimed-rand** [comment]
I guess it's something important for the program is missing. Try to re-install it (uninstall first, then install it again). If still have same problems, check your openJDK versions and make sure it's latest. Or if still same as above, you can ask it on [IDEA Community Forum](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200382555-IntelliJ-IDEA-Users) instead here.

**Comment by jimed-rand** [comment]
Anyway, according to what I see from the error and I also trying install, there are important file `product-info.json` was missing during packaging. So, I'll fix the pacscripts about include that important JSON scripts. Without that, any JetBrains IDE which installed via Pacstall will not running without `product-info.json`.

**Comment by mortim** [comment]
> Anyway, according to what I see from the error and I also trying install, there are important file `product-info.json` was missing during packaging. So, I'll fix the pacscripts about include that important JSON scripts. Without that, any JetBrains IDE which installed via Pacstall will not running without `product-info.json`.

Thx !

**Comment by jimed-rand** [comment]
After my commit has been merged, this broken issue will close as completed and fixed.

**Comment by mortim** [comment]
> After my commit has been merged, this broken issue will close as completed and fixed.

Okay thx
